export const GET_STREETS = 'STREETS/GET_STREETS';
export const GET_HOUSENUMBER = 'HOUSE/GET_HOUSENUMBER';
export const GET_FLATSNUMBER = 'FLATS/GET_FLATSNUMBER';
export const GET_SINGLEFLATNUMBER = 'FLATS/GET_SINGLEFLATNUMBER';
